services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: ai_chatbot_company
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.15.5
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data:
